---
# tasks file for sample-apache
- name: Install pkg 
  yum: 
    name: 
      - httpd
      - mod_ssl 
      - php
      - firewalld
    state: present 

- name: Started and enabled service 
  service: 
    name: "{{ item }}"
    state: started 
    enabled: yes 
  loop: 
    - httpd
    - firewalld

- name: Allow traffic 
  firewalld: 
    service: "{{ item }}"
    immediate: yes 
    state: enabled 
    permanent: yes 
  with_items: 
    - http
    - https 

- name: generate config file 
  template: 
    src: index.html.j2
    dest: /var/www/html/index.html
    backup: yes 
  notify: restarted httpd

