---
- name: Use Archive
  hosts: node2
  become: yes 
  tasks: 
    - name: create a file with content
      file: 
        path: /mnt/mysql_backups/
        state: directory

    - copy: 
        content: "dev,test,qa,prod"
        dest: /mnt/mysql_backups/database_list.txt

    - name: Archive the file created 
      archive: 
        path: /mnt/mysql_backups/database_list.txt
        dest: /mnt/mysql_backups/archive.gz

      
