---
- name: Use a download role 
  hosts: proxy 
  become: yes 
  roles: 
    - roles/haproxy
  vars: 
    haproxy_backend_servers:
        - name: node3
          address: 192.168.1.63:80
        - name: node4
          address: 192.168.1.64:80

    haproxy_backend_balance_method: 'roundrobin'

  post_tasks: 
    - name: Allow traffic 
      firewalld: 
        port: 80/tcp
        immediate: yes 
        permanent: yes 
        state: enabled 

  
