---
- name: Create and use template to create customised config fil
  hosts: all
  become: yes 
  tasks: 
    - name: Create config file 
      template: 
        src: server_list.j2
        dest: /etc/server_list.txt
        owner: automation 
        mode: 0600
        setype: 'net_conf_t'
      delegate_to: node2
