---
- name: Use conditional to controle play Execution 
  hosts: all
  become: yes 
  tasks: 
    - name: Server has more than RAM
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present
      when: 
        - ansible_memtotal_mb > 2048 

    - name: Server has less RAM
      assert:
        that:
          - ansible_memtotal_mb <  2048
        success_msg: "Server Memory less than 2048mb"



