- name: Create a partition
  parted: 
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present
    part_end: 800MB

- name: Create volum group
  lvg:
    vg: vg_database
    pvs: /dev/sdb1

- name: Create logical volum
  lvol: 
    vg: vg_database
    lv: lv_mysql
    size: 512m

- name: Create file system
  filesystem: 
    fstype: xfs
    dev: /dev/vg_database/lv_mysql

- name: Mount the filesystem
  block: 
    - name: create mount point
      file: 
        path: /mnt/mysql_backups
        state: directory

    - name: mount it permanently
      mount: 
        path: /mnt/mysql_backups
        src: /dev/vg_database/lv_mysql
        fstype: xfs
        state: mounted
  


