---
dependencies: []

galaxy_info:
  role_name: repo_ius
  author: David Alger
  description: RPM for IUS Community Project.
  license: MIT
  min_ansible_version: 2.4

  platforms:
    - name: EL
      versions:
        - 7
        - 6

  galaxy_tags:
    - system
    - ius
    - rpm
